# Generated by Django 4.1 on 2022-08-15 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_reserva_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='gender',
        ),
        migrations.AddField(
            model_name='reserva',
            name='alojamiento',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reserva',
            name='guia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reserva',
            name='lancha',
            field=models.BooleanField(default=False),
        ),
    ]
