# Generated by Django 4.1 on 2022-08-15 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_reserva_gender_reserva_alojamiento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='alojamiento',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='guia',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='lancha',
        ),
    ]
