# Generated by Django 4.1 on 2022-08-15 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_reserva_guia'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='alojamiento',
            field=models.BooleanField(default=False, verbose_name='Incluir alojamiento'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='lancha',
            field=models.BooleanField(default=False, verbose_name='Incluir servicio de lancha'),
        ),
    ]
