# Generated by Django 4.1 on 2022-08-15 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_reserva_alojamiento_reserva_lancha'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='correo',
            field=models.CharField(max_length=30, null=True, verbose_name='Correo'),
        ),
    ]
