# Generated by Django 4.1 on 2022-08-15 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_reserva_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='telefono',
            field=models.CharField(max_length=13, null=True, verbose_name='Teléfono'),
        ),
    ]
