# Generated by Django 4.1 on 2022-08-15 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_reserva_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='paseo',
            field=models.BooleanField(default=False, verbose_name='Incluir alojamiento'),
        ),
    ]
