# Generated by Django 4.1 on 2022-08-15 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_reserva_paseo'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='fechaFin',
            field=models.DateField(null=True, verbose_name='Fecha Fin'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='fechaInicio',
            field=models.DateField(null=True, verbose_name='Fecha Inicio'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='paseo',
            field=models.BooleanField(default=False, verbose_name='Incluir Paseo'),
        ),
    ]
