# Generated by Django 3.0.7 on 2022-08-16 19:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_reserva_fechafin_reserva_fechainicio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='alojamiento',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='paseo',
        ),
        migrations.AddField(
            model_name='reserva',
            name='adultos',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Adultos'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='carpas',
            field=models.BooleanField(default=False, verbose_name='Incluir Carpas para Sol'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='hospedaje',
            field=models.BooleanField(default=False, verbose_name='Incluir Hospedaje'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='menores',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Menores'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='museo',
            field=models.BooleanField(default=False, verbose_name='Incluir Recorrido por el Museo'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='salinas',
            field=models.BooleanField(default=False, verbose_name='Incluir Recorrido por Pampas Salineras'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='sendero',
            field=models.BooleanField(default=False, verbose_name='Incluir Recorrido por el Sendero Ecologico'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='guia',
            field=models.BooleanField(default=False, verbose_name='Incluir Guía Turístico'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='lancha',
            field=models.BooleanField(default=False, verbose_name='Incluir Recorrido en Lancha'),
        ),
    ]
