# Generated by Django 3.0.7 on 2022-08-16 21:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20220816_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='correo',
            field=models.CharField(max_length=70, null=True, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='menores',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Menores'),
        ),
    ]
